// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgizWNoBfzBSwvqOdR31On3yJVCdDcdM',
    appId: '1:238869763289:web:239e9dcbb37c6bc9a6dac8',
    messagingSenderId: '238869763289',
    projectId: 'new-chat-app-1cfae',
    authDomain: 'new-chat-app-1cfae.firebaseapp.com',
    storageBucket: 'new-chat-app-1cfae.appspot.com',
    measurementId: 'G-FVNB17X5XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxiQgSXPmc5TQ-DpN3Z3WTjXKzQuCscU',
    appId: '1:238869763289:android:f1d7326e4105af51a6dac8',
    messagingSenderId: '238869763289',
    projectId: 'new-chat-app-1cfae',
    storageBucket: 'new-chat-app-1cfae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEnsJNIS_6Cjf2nSxNaCtYJcSkjoVeNhM',
    appId: '1:238869763289:ios:a20974cd8f69df1ea6dac8',
    messagingSenderId: '238869763289',
    projectId: 'new-chat-app-1cfae',
    storageBucket: 'new-chat-app-1cfae.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEnsJNIS_6Cjf2nSxNaCtYJcSkjoVeNhM',
    appId: '1:238869763289:ios:c767cc89106e6d0ba6dac8',
    messagingSenderId: '238869763289',
    projectId: 'new-chat-app-1cfae',
    storageBucket: 'new-chat-app-1cfae.appspot.com',
    iosBundleId: 'com.example.newChatApp.RunnerTests',
  );
}
